#!/bin/bash
# Is the finite-spot transverse leak a ppc artifact? Launch the ppc pair.
#   studies/spot_leak_ppc/run_variants.sh [-g GPU] [ppc ...]
# Each variant is a real run dir under scratch/ with its own config + README, launched
# through scripts/launch.sh so diags/ cannot be shared. The pair shares geometry, beam and
# duration, so the LEAK RATIO between them is the result -- not either leak on its own.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
GPU=0
if [[ "${1:-}" == "-g" ]]; then GPU="$2"; shift 2; fi
PPCS=("$@")
[[ ${#PPCS[@]} -eq 0 ]] && PPCS=(36 144)

for ppc in "${PPCS[@]}"; do
    name="ppc_${ppc}"
    d="$HERE/scratch/$name"
    mkdir -p "$d"
    python - "$HERE" "$d" "$ppc" "$name" <<'PY'
import sys, yaml, math
here, d, ppc, name = sys.argv[1:5]
cfg = yaml.safe_load(open(f"{here}/config.base.yaml"))
cfg["meta"]["run_id"] = name
cfg["meta"]["deck"] = f"inputs_{name}"
cfg["numerics"]["ppc"]["target"] = int(ppc)
cfg["numerics"]["ppc"]["ambient"] = int(ppc)
yaml.safe_dump(cfg, open(f"{d}/config.yaml", "w"), sort_keys=False)
n = int(ppc)
floor = 100.0 / math.sqrt(float(n))
open(f"{d}/README.md", "w").write(f"""# {name} -- transverse-leak ppc variant, {ppc} ppc

**Phase.** 1, follow-up to `runs/P1/P1_vac_2d_spot` (RESULTS 2026-07-29)
**Question.** Does the power that leaks out of a finite spot -- {ppc} ppc here -- scale with
the macroparticle shot noise, which would make it a resolution artifact rather than physics?
**Expected.** The per-cell density shot-noise floor is 1/sqrt({n}) = {floor:.1f} %, and near the
critical surface `n_ref = sqrt(1 - n_e/n_cr)` -> 0 amplifies a density gradient by `1/n_ref`,
so a noise-driven leak should fall with ppc. The physics run measured a 9.4 % transverse
ripple at the critical surface at 36 ppc, i.e. at its own floor.
**Falsified by.** A leak share unchanged across the pair -- then the pedestal is refraction
off a real transverse gradient and belongs in every finite-spot error budget.

## Setup
Generated by `studies/spot_leak_ppc/run_variants.sh` from `config.base.yaml`; the only
difference between variants is `numerics.ppc`. Target thinned to 100 `d_e` and `t_end` cut to
1 ps so that 144 ppc fits in 12 GB of device memory: at 1 ps the rarefaction has crossed only
~4 `d_e` of the slab, so the corona the rays actually refract in is the same one the 400 `d_e`
physics run has at that time.

## Cost
320 x 1000 cells, 14 400 steps. Particle count and therefore the push cost scale with ppc;
the ray march does not.

## Gates
G3 does not apply -- this is a numerical discriminator, not a physics run. G5 is the subject.

## Result
See `studies/spot_leak_ppc/analyze.py` output.

## Retracted
Nothing.
""")
PY
    python "$ROOT/scripts/make_inputs.py" "$d" >/dev/null
    echo "=== launching $name ({$ppc} ppc) on GPU $GPU"
    "$ROOT/scripts/launch.sh" -g "$GPU" -f "$d" >/dev/null 2>&1 || echo "  FAILED $name"
done
echo "pair complete"
