#!/bin/bash
# Launch the rays_per_cell sub-ray sampling ladder for the finite-spot deck.
#   studies/rays_per_cell/run_variants.sh [-g GPU] [rays_per_cell ...]
#
# Each variant is a real run dir under scratch/ with its own config + README, launched
# through scripts/launch.sh so diags/ cannot be shared. max_step = 2 comes from
# config.base.yaml: only the step-0 profile dump is measured.
#
# The plotfile diagnostics are pushed out of range with ParmParse overrides rather than
# edited in the config, because a step-0 plotfile of this deck is 1.6 GB of particles that
# the measurement never reads -- three variants would write 5 GB to throw away. That is
# also why `make_inputs.py --verify` will flag these runs: they are a numerical
# measurement, not physics, and the override is recorded here rather than hidden.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
GPU=0
if [[ "${1:-}" == "-g" ]]; then GPU="$2"; shift 2; fi
RPCS=("$@")
[[ ${#RPCS[@]} -eq 0 ]] && RPCS=(1 2 4)
OFF="diag1.intervals=1000000:2000000 diag_fields.intervals=1000000:2000000 diag_phase.intervals=1000000:2000000"

for rpc in "${RPCS[@]}"; do
    name="rpc_${rpc}"
    d="$HERE/scratch/$name"
    mkdir -p "$d"
    python - "$HERE" "$d" "$rpc" "$name" <<'PY'
import sys, yaml
here, d, rpc, name = sys.argv[1:5]
cfg = yaml.safe_load(open(f"{here}/config.base.yaml"))
cfg["meta"]["run_id"] = name
cfg["meta"]["deck"] = f"inputs_{name}"
cfg["laser"]["beam"]["rays_per_cell"] = int(rpc)
yaml.safe_dump(cfg, open(f"{d}/config.yaml", "w"), sort_keys=False)
n = int(rpc)
open(f"{d}/README.md", "w").write(f"""# {name} -- sub-ray sampling variant, rays_per_cell = {rpc}

**Phase.** 1, `TEST_PLAN.md` 7.2 (rays_per_cell convergence belongs with the finite-spot run)
**Question.** Does one ray per transverse cell sample a Gaussian spot of `w0` = 20 `d_e`
well enough, or does the deposition profile change with sub-cell sampling?
**Expected.** {n} sub-ray(s) per cell per transverse dimension means {n * 2} samples per `d_e`
and {n * 40} per waist. The MEAN column profile should already be converged at
rays_per_cell = 1 (40 samples per waist); what should fall is the column-to-column
SCATTER, which is set by how far an individual ray wanders through the density ripple
rather than by how many rays there are.
**Falsified by.** A change in the mean absorbed power, or in the measured 1/e radius, with
rays_per_cell -- that would put the finite-spot run's transverse profile in question.

## Setup
Generated by `studies/rays_per_cell/run_variants.sh` from `config.base.yaml`; the only
difference between variants is `laser.beam.rays_per_cell`. Geometry, target, beam waist and
ppc are the physics run's (`runs/P1/P1_vac_2d_spot`) so the result transfers to it directly.
`max_step` = 2: only the step-0 dump is measured, against the initial analytic density.

## Cost
320 x 2200 cells, ~26.8 M macroparticles, 2 steps -- dominated by particle initialisation.
The ray march cost scales as rays_per_cell (in 2D), so this ladder is cheap only because it
is two steps long.

## Gates
G3 (laser-off control) does not apply: this is a numerical measurement of the operator, not
a physics run. The plotfile diagnostics are disabled by ParmParse override, so
`make_inputs.py --verify` will flag the deck -- by design, see `run_variants.sh`.

## Result
See `studies/rays_per_cell/analyze.py` output and `media/rays_per_cell/`.

## Retracted
Nothing.
""")
PY
    python "$ROOT/scripts/make_inputs.py" "$d" -q >/dev/null 2>&1 || python "$ROOT/scripts/make_inputs.py" "$d" >/dev/null
    echo "=== launching $name (rays_per_cell = $rpc) on GPU $GPU"
    "$ROOT/scripts/launch.sh" -g "$GPU" -f "$d" -- $OFF >/dev/null 2>&1 || echo "  FAILED $name"
done
echo "ladder complete"
