#!/bin/bash
# Launch the ray_cfl ladder for the exit-boundary overshoot measurement.
#   studies/exit_overshoot/run_variants.sh [ray_cfl ...]
# Each variant is a real run dir under scratch/ with its own config + README, launched
# through scripts/launch.sh so diags/ cannot be shared.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
CFLS=("${@:-}")
[[ -z "${CFLS[0]:-}" ]] && CFLS=(0.05 0.1 0.25 0.5 1.0)

for rc in "${CFLS[@]}"; do
    name="raycfl_${rc}"
    d="$HERE/scratch/$name"
    mkdir -p "$d"
    python - "$HERE" "$d" "$rc" "$name" <<'PY'
import sys, yaml
here, d, rc, name = sys.argv[1:5]
cfg = yaml.safe_load(open(f"{here}/config.base.yaml"))
cfg["meta"]["run_id"] = name
cfg["meta"]["deck"] = f"inputs_{name}"
cfg["laser"]["ray_cfl"] = float(rc)
yaml.safe_dump(cfg, open(f"{d}/config.yaml", "w"), sort_keys=False)
open(f"{d}/README.md", "w").write(f"""# {name} — exit-overshoot variant, ray_cfl = {rc}

**Phase.** 0, `TEST_PLAN.md` §5.1 item 3
**Question.** How much energy does the ray tracer CREATE in the final cell at the exit
face, at ray_cfl = {rc}?
**Expected.** The domain-exit test runs after the step's deposit, so one full arc-length
step of length `ray_cfl x dz` is deposited beyond the boundary and clamped into the last
cell. The excess should therefore scale roughly linearly with ray_cfl.
**Falsified by.** No excess in the final cell, or an excess independent of ray_cfl.

## Setup
Generated by `studies/exit_overshoot/run_variants.sh` from `config.base.yaml`; the only
difference between variants is `laser.ray_cfl`. Uniform underdense slab (0.5 n_cr) filling
the domain so the ray transits and exits at z = lo. `temperature_mode: fixed` and a
1e14 W/m^2 probe keep the profile static, so the analytic march is exact.

## Cost
400 cells, 2 species x 200 ppc, 2 steps — seconds.

## Gates
Pre-run gates are reported by `run_checks.py`; this run is a numerical measurement, not
physics, so G3 (laser-off control) does not apply.

## Result
See `studies/exit_overshoot/analyze.py` output and `media/exit_overshoot/`.

## Retracted
Nothing.
""")
PY
    python "$ROOT/scripts/make_inputs.py" "$d" -q >/dev/null
    echo "=== launching $name (ray_cfl = $rc)"
    "$ROOT/scripts/launch.sh" -j 2 "$d" >/dev/null 2>&1 || echo "  FAILED $name"
done
echo "ladder complete"
