#!/usr/bin/env python3
"""The ppc ladder (decision D6) -- declared in P4_lez_kin's config, never run.

    /opt/anaconda3/envs/physics/bin/python studies/ppc_ladder/make_ladder.py
    ... make_ladder.py --ppc 500 2000 10000 --launch --gpu 0

WHAT IS BEING TESTED. The one quantity still in dispute between FLASH and WarpX is the
SHAPE of T_e: FLASH is a flat isothermal plateau, WarpX rises outward with a hot tail. A
per-cell temperature is a sample moment, so before that tail is called physics it has to
survive more particles.

WHY THE PPC NUMBERS ARE NOT COMPARABLE TO THE PAPER'S, and what is matched instead.
Lezhnin 2025 loads "10^5 EQUALLY WEIGHTED particles per cell per species at critical
density" -- uniform weight, so the particle count scales with the local density:

    n/n_cr      10      1     0.1    1e-2    1e-3    1e-4    1e-5
    PSC ppc     1e6    1e5    1e4    1e3     100      10       1
    ours (500)  500    500    500    500     500     500     500

So PSC has 2000x our statistics in the target and 200x at critical -- but BELOW ~5e-3 n_cr
we have MORE than they do, and that is exactly where the disputed hot tail lives. Matching
their ppc number is therefore neither possible (3.4e8 macroparticles/species at 1e5, ~70 GB)
nor the right target. What IS comparable is the RESOLVED DYNAMIC RANGE: PSC spans six
decades (10 n_cr down to a 1e-5 n_cr floor, where one macroparticle per cell remains); our
default `density_min` = 1e-4*n_t spans four. Every rung here sets
`numerics.density_min_frac` = 1e-6 to span the same six decades, and then varies ppc to
vary the noise at fixed range.

READ: does the outward T_e rise weaken as ppc goes up? If it does, it was sampling noise
and no closure argument is needed. If it survives 20x the particles, it is kinetic
transport and D2b/D3-Appendix-C are the follow-ups.
"""
from __future__ import annotations
import argparse, os, shutil, subprocess, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
BASE = os.path.join(ROOT, "runs", "P4", "P4_lez_kin")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "scratch")
PY = "/opt/anaconda3/envs/physics/bin/python"


def variant(ppc, dmf):
    rid = f"L_ppc{ppc}"
    d = os.path.join(OUT, rid)
    os.makedirs(d, exist_ok=True)
    src = open(os.path.join(BASE, "config.yaml")).read()
    src = src.replace("  run_id: P4_lez_kin\n", f"  run_id: {rid}\n", 1)
    src = src.replace("  deck: inputs_P4_lez_kin\n", f"  deck: inputs_{rid}\n", 1)
    # ppc
    old = "    target: 500"
    assert src.count(old) == 1, "ppc anchor moved"
    src = src.replace(old, f"    target: {ppc}")
    # dynamic range: six decades, as the paper
    src = src.replace("  cfl: 0.35",
                      f"  density_min_frac: {dmf:g}\n"
                      f"  arena_init_size_mb: 4096\n"
                      f"  cfl: 0.35", 1)
    # The cap is not optional for a LADDER. AMReX pre-allocates 3/4 of the card's TOTAL
    # memory in one cudaMalloc, so the FIRST rung on a device takes 8.9 GB of an RTX 4070
    # and every later rung aborts at init with "Arena out of memory" -- which is exactly
    # what happened the first time this ladder was launched. 4 GiB is ample for 10000 ppc
    # here and lets rungs share a card.
    # the gate would otherwise refuse a rung below its own floor
    src = src.replace("  ppc_target_min: 500", f"  ppc_target_min: {min(ppc, 500)}")
    open(os.path.join(d, "config.yaml"), "w").write(src)
    open(os.path.join(d, "README.md"), "w").write(f"""# {rid} — ppc ladder rung

**Study.** `studies/ppc_ladder/` — decision D6, declared in `P4_lez_kin`'s config and never
run until now. Generated by `make_ladder.py`; **do not hand-edit.**

**Question.** Does WarpX's outward-rising `T_e` — the last unexplained difference against
FLASH — weaken as the particle count rises? A per-cell temperature is a sample moment, and
the tail lives where the plume is most rarefied.

**This rung.** `ppc` = {ppc}, `density_min_frac` = {dmf:g} (six decades of resolved density,
matching the paper's range; the project default of 1e-4 gives four). Everything else is
`P4_lez_kin` unchanged.

**Note on the paper's ppc.** Not comparable as a number: PSC loads equally weighted
particles so its ppc scales with density (1e6 in the target, 1 at its 1e-5 floor). Below
~5e-3 `n_cr` our fixed ppc gives MORE particles than PSC has. The dynamic range is what is
matched here, not the count.

## Result
_Pending._
""")
    return d


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ppc", type=int, nargs="+", default=(500, 2000, 10000))
    ap.add_argument("--density-min-frac", dest="dmf", type=float, default=1.0e-6)
    ap.add_argument("--launch", action="store_true")
    ap.add_argument("--gpu", type=int, default=0)
    ap.add_argument("--clean", action="store_true", help="remove scratch/ first")
    a = ap.parse_args()

    if a.clean and os.path.isdir(OUT):
        shutil.rmtree(OUT)
    made = []
    for ppc in a.ppc:
        d = variant(ppc, a.dmf)
        r = subprocess.run([PY, os.path.join(ROOT, "scripts", "make_inputs.py"), d, "-q"],
                           capture_output=True, text=True)
        print(f"  {os.path.basename(d):16s} {'OK' if r.returncode == 0 else 'FAILED'}")
        if r.returncode:
            print(r.stdout[-1500:], r.stderr[-1500:]); return 1
        made.append(d)
    if not a.launch:
        print("\n  --launch to start them (one at a time; --gpu to choose the device)")
        return 0
    for d in made:
        r = subprocess.run([os.path.join(ROOT, "scripts", "launch.sh"), "-b", "-L",
                            "-g", str(a.gpu), d], capture_output=True, text=True)
        print(r.stdout[-400:] or r.stderr[-400:])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
